architecture: DAMSDET_Rotate_Paired_DAOD
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
ema_filter_no_grad: True
hidden_dim: 256
use_focal_loss: True
#eval_size: [640, 640]
#eval_size: [1024, 1024]

DAMSDET_Rotate_Paired_DAOD:
#  backbone: ResNet
#  neck: HybridEncoder
#  transformer: RTDETRTransformer_Rotate
#  detr_head: DINOHead_Rotate_DAOD
#  post_process: DETRPostProcess_Rotate
  backbone_stream1: ResNet
  backbone_stream2: ResNet
  neck_stream1: HybridEncoder
  neck_stream2: HybridEncoder
  transformer_single: RTDETRTransformer_Rotate
  transformer_DPDETR: Multi_RTDETRTransformer_Rotate_Paired_Decouple_atten
  detr_head_single: DINOHead_Rotate_DAOD
  detr_head_DPDETR: DINOHead_Rotate_Paired_DAOD
  post_process: DETRPostProcess_Rotate
  post_process_paired: DETRPostProcess_Rotate_Paired

ResNet:
  # index 0 stands for res2
  depth: 50
  variant: d
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.1, 0.1, 0.1, 0.1]
  num_stages: 4
  freeze_stem_only: True

HybridEncoder:
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  encoder_layer:
    name: TransformerLayer
    d_model: 256
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.
    activation: 'gelu'
  expansion: 1.0

Multi_RTDETRTransformer_Rotate_Paired_Decouple_atten:
  num_queries: 300
  position_embed_type: sine
  feat_strides: [ 8, 16, 32 ]
  num_levels: 3

  visir_feat_strides: [ 8, 16, 32, 8, 16, 32 ]
  num_visir_levels: 6
  proj_all: False

  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.0
  activation: relu
  num_denoising: 100
  #num_denoising: 0
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  angle_noise_scale: 0.03
  learnt_init_query: False

RTDETRTransformer_Rotate:
  num_queries: 300
  position_embed_type: sine
  feat_strides: [8, 16, 32]
  num_levels: 3
  nhead: 8
  num_decoder_layers: 6
  dim_feedforward: 1024
  dropout: 0.0
  activation: relu
  num_denoising: 100
  #num_denoising: 0
  label_noise_ratio: 0.5
  box_noise_scale: 1.0
  angle_noise_scale: 0.03
  learnt_init_query: False

DINOHead_Rotate_DAOD:
  loss:
    name: DINOLoss_Rotate
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    use_vfl: True
    matcher:
      name: HungarianMatcher_Rotate
      matcher_coeff: {class: 2, bbox: 5, giou: 2}
      
DINOHead_Rotate_Paired_DAOD:
  loss:
    name: DINOLoss_Rotate_Paired
    loss_coeff: {class: 1, bbox: 5, giou: 2}
    aux_loss: True
    use_vfl: True
    matcher:
      name: HungarianMatcher_Rotate_Paired
      matcher_coeff: {class: 2, bbox: 5, giou: 2}
      
DETRPostProcess_Rotate:
  num_top_queries: 300

DETRPostProcess_Rotate_Paired:
  num_top_queries: 300