metric: RBOX
num_classes: 5
#/data1/jinhang/Datasets/rbox_Drone_Vehicle
# TrainDataset:
#   !Mutisprctral_COCODataSet_Paired
#     vis_image_dir: train/trainimg
#     ir_image_dir : train/trainimgr
#     anno_path_vis: train_vis_segmentation.json
#     anno_path_ir: train_ir_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']
#     #allow_empty: true

# EvalDataset2:
#   !Mutisprctral_COCODataSet_Paired
#     vis_image_dir: val/valimg
#     ir_image_dir: val/valimgr
#     anno_path_vis: val_vis_segmentation.json
#     anno_path_ir: val_ir_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']

# EvalDataset:
#   !Mutisprctral_COCODataSet
#     vis_image_dir: val/valimg
#     ir_image_dir: val/valimgr
#     anno_path: val_ir_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
#     #allow_empty: true

# TestDataset:
#   !Multi_ImageFolder
#     anno_path: label_list.txt # also support txt (like VOC's label_list.txt)
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle # if set, anno_path will be 'dataset_dir/anno_path'
# #######################################
###########红外和可见光互换#############
#######################################
# metric: RBOX
# num_classes: 5
# #/data1/jinhang/Datasets/rbox_Drone_Vehicle
# TrainDataset:
#   !Mutisprctral_COCODataSet_Paired
#     vis_image_dir: train/trainimgr
#     ir_image_dir : train/trainimg
#     anno_path_vis: train_ir_segmentation.json
#     anno_path_ir: train_vis_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']
#     #allow_empty: true

# EvalDataset2:
#   !Mutisprctral_COCODataSet_Paired
#     vis_image_dir: val/valimgr
#     ir_image_dir: val/valimg
#     anno_path_vis: val_ir_segmentation.json
#     anno_path_ir: val_vis_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']

# EvalDataset:
#   !Mutisprctral_COCODataSet
#     vis_image_dir: val/valimgr
#     ir_image_dir: val/valimg
#     anno_path: val_vis_segmentation.json
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
#     data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
#     #allow_empty: true

# TestDataset:
#   !Multi_ImageFolder
#     anno_path: label_list.txt # also support txt (like VOC's label_list.txt)
#     dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle # if set, anno_path will be 'dataset_dir/anno_path'
#################################
###########ioumax数据集###########
#################################
metric: RBOX
num_classes: 5
#/data1/jinhang/Datasets/rbox_Drone_Vehicle
TrainDataset:
  !Mutisprctral_COCODataSet_Paired
    vis_image_dir: train/trainimg
    ir_image_dir : train/trainimgr
    anno_path_vis: train_vis_segmentation_paired.json
    anno_path_ir: train_ir_segmentation_paired.json
    dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
    data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']
    #allow_empty: true

EvalDataset2:
  !Mutisprctral_COCODataSet_Paired
    vis_image_dir: val/valimg
    ir_image_dir: val/valimgr
    anno_path_vis: val_vis_segmentation_paired.json
    anno_path_ir: val_ir_segmentation_paired.json
    dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
    data_fields: ['image', 'gt_bbox_vis','gt_bbox_ir', 'gt_class', 'is_crowd', 'gt_poly_vis','gt_poly_ir']

EvalDataset:
  !Mutisprctral_COCODataSet
    vis_image_dir: val/valimg
    ir_image_dir: val/valimgr
    anno_path: val_ir_segmentation_paired.json
    dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
    #allow_empty: true

TestDataset:
  !Multi_ImageFolder
    anno_path: label_list.txt # also support txt (like VOC's label_list.txt)
    dataset_dir: /data1/jinhang/Datasets/rbox_Drone_Vehicle # if set, anno_path will be 'dataset_dir/anno_path'